package game;


public enum Card {
	ACE_SPADE, TWO_SPADE, THREE_SPADE, FOUR_SPADE, FIVE_SPADE, SIX_SPADE, SEVEN_SPADE, EIGHT_SPADE, NINE_SPADE, TEN_SPADE, JACK_SPADE, QUEEN_SPADE, KING_SPADE,
	ACE_HEART, TWO_HEART, THREE_HEART, FOUR_HEART, FIVE_HEART, SIX_HEART, SEVEN_HEART, EIGHT_HEART, NINE_HEART, TEN_HEART, JACK_HEART, QUEEN_HEART, KING_HEART,
	ACE_DIAMOND, TWO_DIAMOND, THREE_DIAMOND, FOUR_DIAMOND, FIVE_DIAMOND, SIX_DIAMOND, SEVEN_DIAMOND, EIGHT_DIAMOND, NINE_DIAMOND, TEN_DIAMOND, JACK_DIAMOND, QUEEN_DIAMOND, KING_DIAMOND,
	ACE_CLUB, TWO_CLUB, THREE_CLUB, FOUR_CLUB, FIVE_CLUB, SIX_CLUB, SEVEN_CLUB, EIGHT_CLUB, NINE_CLUB, TEN_CLUB, JACK_CLUB, QUEEN_CLUB, KING_CLUB,
	JOKER;
}
